version: 2.1
jobs:
    build:
        working_directory: ~/aaarray
        docker:
            - image: circleci/node:12.6.0
        steps:
            - checkout
            - restore_cache:
                name: Restore Yarn Package Cache
                keys:
                    - yarn-packages-{{ checksum "yarn.lock" }}
            - run:
                name: Install Dependencies
                command: yarn install --frozen-lockfile
            - save_cache:
                name: Save Yarn Package Cache
                key: yarn-packages-{{ checksum "yarn.lock" }}
                paths:
                    - ~/.cache/yarn
            - run:
                name: Run Tests
                command: yarn test-ci
            - store_test_results:
                path: reports/junit
            - run:
                name: Coverage Report
                command: yarn coveralls

