name: CI
on: [push, pull_request]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_versions: [10, 11, 12, 13]
      fail-fast: true
    
    steps:
      - uses: actions/checkout@v1

      - name: Use node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node_version }}
      
      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test-ci
      
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          path-to-lcov: reports/lcov/lcov.info
      
      - name: Coveralls Complete
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
          path-to-lcov: reports/lcov/lcov.info


